services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: landis-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: landis
      POSTGRES_PASSWORD: landis123
      POSTGRES_DB: landis

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: